/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import DTOs.CursoDTO;
import DTOs.InscripcionDTO;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jp
 */
public class DialogoFichaPago extends javax.swing.JDialog {

    /**
     * Creates new form DialogoFichaPago
     *
     * @param parent
     * @param modal
     * @param inscripcion
     */
    public DialogoFichaPago(java.awt.Frame parent, boolean modal, InscripcionDTO inscripcion) {
        super(parent, modal);
        initComponents();
        
        for (CursoDTO curso : inscripcion.getCursosInscritos()) {
            contenedorCursos.add(getPanelCurso(curso.getNombre(), curso.getCosto()));
        }
        labelTotal.setText("$" + String.format("%.2f", inscripcion.getCostoTotal()));
        
        this.pack();
        this.setLocationRelativeTo(parent);
    }

    private JPanel getPanelCurso(String nombre, double precio) {
        return new JPanel() {
            {
                setBackground(Color.WHITE);
                setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 40));
                
                JLabel nombreCurso = new javax.swing.JLabel();
                JLabel precioCurso = new javax.swing.JLabel();

                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                nombreCurso.setFont(new java.awt.Font("Segoe UI", 0, 16));
                nombreCurso.setForeground(new java.awt.Color(91, 91, 91));
                nombreCurso.setText(nombre);
                add(nombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, -1));

                precioCurso.setFont(new java.awt.Font("Segoe UI", 0, 16));
                precioCurso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                precioCurso.setText("$" + String.format("%.2f", precio));
                add(precioCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, -1));
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        separadorTitulo = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        contenedorCursos = new javax.swing.JPanel();
        separadorTotal = new javax.swing.JSeparator();
        labelTextoCostoTotal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha de pago");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setModal(true);
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setMaximumSize(new java.awt.Dimension(488, 630));
        panelBackground.setMinimumSize(new java.awt.Dimension(488, 630));
        panelBackground.setPreferredSize(new java.awt.Dimension(488, 630));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26)); // NOI18N
        labelTitulo.setText("Ficha de pago");
        panelBackground.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(107, 107, 107));
        labelDescripcion.setText("Resumen de tu inscripción");
        panelBackground.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        panelBackground.add(separadorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 440, -1));

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setFocusable(false);
        scroll.setHorizontalScrollBar(null);

        contenedorCursos.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCursos.setLayout(new javax.swing.BoxLayout(contenedorCursos, javax.swing.BoxLayout.Y_AXIS));
        scroll.setViewportView(contenedorCursos);

        panelBackground.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 440, 450));
        panelBackground.add(separadorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 440, -1));

        labelTextoCostoTotal.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        labelTextoCostoTotal.setText("Costo Total:");
        panelBackground.add(labelTextoCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, 50));

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(99, 102, 241));
        labelTotal.setText("$0000.00");
        panelBackground.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        getContentPane().add(panelBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorCursos;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelTextoCostoTotal;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separadorTitulo;
    private javax.swing.JSeparator separadorTotal;
    // End of variables declaration//GEN-END:variables
}
