/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.IControladorInscripcion;
import javax.swing.Box;

/**
 *
 * @author Jp
 */
public class PanelCursosDisponibles extends javax.swing.JPanel {

    private final int ESPACIO_ENTRE_CURSOS = 11;

    private IControladorInscripcion controlador;

    public PanelCursosDisponibles() {
        initComponents();
    }

    public void agregarCurso(int id, String nombre, double precio) {

        panelContenedorCursos.add(new PanelCurso(id, nombre, precio, true, controlador));
        panelContenedorCursos.add(Box.createVerticalStrut(ESPACIO_ENTRE_CURSOS));
    }

    public void quitarTodosLosCursos() {
        panelContenedorCursos.removeAll();
        panelContenedorCursos.revalidate();
        panelContenedorCursos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorTitulo = new javax.swing.JSeparator();
        labelTitulo = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        panelContenedorCursos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 2, true));
        setMaximumSize(new java.awt.Dimension(488, 523));
        setMinimumSize(new java.awt.Dimension(488, 523));
        setPreferredSize(new java.awt.Dimension(488, 523));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(separadorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 430, -1));

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelTitulo.setText("Cursos Disponibles");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelContenedorCursos.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedorCursos.setLayout(new javax.swing.BoxLayout(panelContenedorCursos, javax.swing.BoxLayout.Y_AXIS));
        scroll.setViewportView(panelContenedorCursos);

        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 430, 390));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelContenedorCursos;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separadorTitulo;
    // End of variables declaration//GEN-END:variables

    public void setControlador(IControladorInscripcion controlador) {
        this.controlador = controlador;
    }
}
