/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.IControladorInscripcion;
import javax.swing.Box;

/**
 *
 * @author Jp
 */
public class PanelCursosInscritos extends javax.swing.JPanel {

    private final int ESPACIO_ENTRE_CURSOS = 11;
    private double total = 0;

    private IControladorInscripcion controlador;

    public PanelCursosInscritos() {
        initComponents();
    }

    public void agregarCurso(int id, String nombre, double precio) {
        panelContenedorCursos.add(new PanelCurso(id, nombre, precio, false, controlador));
        panelContenedorCursos.add(Box.createVerticalStrut(ESPACIO_ENTRE_CURSOS));

        this.total += precio;
        actualizarLabelCantidadTotal();
        
        botonFinalizarInscripcion.setEnabled(true);
    }

    public void quitarTodosLosCursos() {
        panelContenedorCursos.removeAll();
        panelContenedorCursos.revalidate();
        panelContenedorCursos.repaint();

        total = 0;
        actualizarLabelCantidadTotal();

        botonFinalizarInscripcion.setEnabled(false);
    }

    private void actualizarLabelCantidadTotal() {
        this.labelCantidadTotal.setText("$" + String.format("%.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorTitulo = new javax.swing.JSeparator();
        labelTitulo = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        panelContenedorCursos = new javax.swing.JPanel();
        separadorCostoTotal = new javax.swing.JSeparator();
        labelTotalPagar = new javax.swing.JLabel();
        labelCantidadTotal = new javax.swing.JLabel();
        botonFinalizarInscripcion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 2, true));
        setMaximumSize(new java.awt.Dimension(488, 523));
        setMinimumSize(new java.awt.Dimension(488, 523));
        setPreferredSize(new java.awt.Dimension(488, 523));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(separadorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 430, -1));

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelTitulo.setText("Cursos Inscritos");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelContenedorCursos.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedorCursos.setLayout(new javax.swing.BoxLayout(panelContenedorCursos, javax.swing.BoxLayout.Y_AXIS));
        scroll.setViewportView(panelContenedorCursos);

        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 430, 310));
        add(separadorCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 430, -1));

        labelTotalPagar.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        labelTotalPagar.setForeground(new java.awt.Color(107, 107, 107));
        labelTotalPagar.setText("Total a Pagar:");
        add(labelTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        labelCantidadTotal.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        labelCantidadTotal.setForeground(new java.awt.Color(99, 102, 241));
        labelCantidadTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCantidadTotal.setText("$0,000.00");
        add(labelCantidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 400, 220, -1));

        botonFinalizarInscripcion.setBackground(new java.awt.Color(99, 102, 241));
        botonFinalizarInscripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonFinalizarInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        botonFinalizarInscripcion.setText("Finalizar Inscripción");
        botonFinalizarInscripcion.setEnabled(false);
        botonFinalizarInscripcion.setFocusable(false);
        botonFinalizarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarInscripcionActionPerformed(evt);
            }
        });
        add(botonFinalizarInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 432, 47));
    }// </editor-fold>//GEN-END:initComponents

    private void botonFinalizarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarInscripcionActionPerformed
        controlador.finalizarInscripcion();
    }//GEN-LAST:event_botonFinalizarInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFinalizarInscripcion;
    private javax.swing.JLabel labelCantidadTotal;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTotalPagar;
    private javax.swing.JPanel panelContenedorCursos;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separadorCostoTotal;
    private javax.swing.JSeparator separadorTitulo;
    // End of variables declaration//GEN-END:variables

    public void setControlador(IControladorInscripcion controlador) {
        this.controlador = controlador;
    }
}
