/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorInscripcion;
import controlador.IControladorInscripcion;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Jp
 */
public class PanelCurso extends javax.swing.JPanel {

    private final Color BACKGROUND_NORMAL = new Color(249, 250, 251);
    private final Color HOVER_DISPONIBLE = new Color(238, 242, 255);
    private final Color HOVER_INSCRITO = new Color(240, 253, 244);

    private int id;
    private double precioCurso;
    private boolean cursoDisponible;
    private ImageIcon icono;

    private IControladorInscripcion controlador;

    /**
     * Creates new form PanelCurso
     *
     * @param id
     * @param nombre
     * @param precio
     * @param cursoDisponible
     * @param controlador
     */
    public PanelCurso(int id, String nombre, double precio, boolean cursoDisponible, IControladorInscripcion controlador) {
        initComponents();

        this.id = id;
        this.precioCurso = precio;
        this.cursoDisponible = cursoDisponible;
        this.controlador = controlador;

        agregarEventosMouse();
        cargarIcons();
        this.labelNombreCurso.setText(nombre);
        this.labelPrecioCurso.setText("$" + String.format("%.2f", precioCurso));
    }

    private void agregarEventosMouse() {
        this.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (cursoDisponible) {
                    setBackground(HOVER_DISPONIBLE);
                } else {
                    setBackground(HOVER_INSCRITO);
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setBackground(BACKGROUND_NORMAL);
            }

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (cursoDisponible) {
                    controlador.inscribirCurso(id);
                } else {
                    controlador.quitarCurso(id);
                }
            }
        });
    }

    public double getPrecioCurso() {
        return precioCurso;
    }

    private void cargarIcons() {
        if (cursoDisponible) {
            icono = new ImageIcon(getClass().getResource("/icons/add.png"));
        } else {
            icono = new ImageIcon(getClass().getResource("/icons/remove.png"));
        }

        labelIcon.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPrecioCurso = new javax.swing.JLabel();
        labelNombreCurso = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 250, 251));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 107, 107), 1, true));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(390, 64));
        setMinimumSize(new java.awt.Dimension(390, 64));
        setPreferredSize(new java.awt.Dimension(390, 64));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPrecioCurso.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        labelPrecioCurso.setForeground(new java.awt.Color(107, 107, 107));
        labelPrecioCurso.setText("$0,000.00");
        labelPrecioCurso.setMaximumSize(new java.awt.Dimension(330, 21));
        add(labelPrecioCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, -1));

        labelNombreCurso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombreCurso.setText("Nombre curso");
        labelNombreCurso.setMaximumSize(new java.awt.Dimension(330, 25));
        labelNombreCurso.setMinimumSize(new java.awt.Dimension(330, 25));
        labelNombreCurso.setPreferredSize(new java.awt.Dimension(330, 25));
        add(labelNombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 20));
        add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 30, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelNombreCurso;
    private javax.swing.JLabel labelPrecioCurso;
    // End of variables declaration//GEN-END:variables
}
