/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DTOs.InscripcionDTO;
import controlador.IControladorInscripcion;
import observer.IObserver;

/**
 *
 * @author Jp
 */
public class VentanaPrincipal extends javax.swing.JFrame implements IObserver {

    private IControladorInscripcion controlador;

    /**
     * Creates new form VentanaPrincipal
     *
     */
    public VentanaPrincipal() {
        initComponents();
    }

    public void setControlador(IControladorInscripcion controlador) {
        this.controlador = controlador;
        panelCursosDisponibles.setControlador(controlador);
        panelCursosInscritos.setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelCursosInscritos = new vista.PanelCursosInscritos();
        panelCursosDisponibles = new vista.PanelCursosDisponibles();
        labelTitulo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscripción a Cursos");
        setMinimumSize(new java.awt.Dimension(1336, 768));
        setName("ventanaPrincipal"); // NOI18N
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(243, 244, 246));
        panelFondo.setFocusable(false);
        panelFondo.setMinimumSize(new java.awt.Dimension(1336, 768));

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 40)); // NOI18N
        labelTitulo.setText("Inscripción a Cursos");

        labelDescripcion.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(107, 107, 107));
        labelDescripcion.setText("Selecciona los cursos a inscribir");

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(panelCursosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(panelCursosInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(484, 484, 484)
                .addComponent(labelTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(labelDescripcion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCursosInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCursosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelTitulo;
    private vista.PanelCursosDisponibles panelCursosDisponibles;
    private vista.PanelCursosInscritos panelCursosInscritos;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(Object estado) {
        if (estado instanceof InscripcionDTO inscripcionDTO) {

            panelCursosDisponibles.quitarTodosLosCursos();
            panelCursosInscritos.quitarTodosLosCursos();

            inscripcionDTO.getCursosDisponibles().forEach(curso -> {
                panelCursosDisponibles.agregarCurso(curso.getId(), curso.getNombre(), curso.getCosto());
            });

            inscripcionDTO.getCursosInscritos().forEach(curso -> {
                panelCursosInscritos.agregarCurso(curso.getId(), curso.getNombre(), curso.getCosto());
            });

        }
    }
}
